name: Keepalive Workflow

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Keepalive Workflow
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit --allow-empty -m "Chore: Keep-alive [skip ci]"
          git push || echo "No changes to push"
